parameters:
    APP_SETTINGS_APP_ENV:             'prod'
    APP_SETTINGS_APP_SECRET:          'TEMPORARY_SECRET'
    APP_SETTINGS_DATABASE_URL:        ''
    APP_SETTINGS_MAILER_URL:          ''
    APP_SETTINGS_CACHE_APP:           'cache.adapter.filesystem'
    APP_SETTINGS_REDIS_CACHE_DB:      ''
    APP_SETTINGS_REDIS_CACHE_HOST:    ''
    APP_SETTINGS_REDIS_CACHE_PORT:    ''
    APP_SETTINGS_REDIS_SESSION_DB:    ''
    APP_SETTINGS_REDIS_SESSION_HOST:  ''
    APP_SETTINGS_REDIS_SESSION_PORT:  ''
