parameters:
    APP_SETTINGS_APP_ENV:             'dev'
    APP_SETTINGS_APP_SECRET:          'ce96b39e4a36d3541ec8b232186267ee'
    APP_SETTINGS_CACHE_APP:           'cache.adapter.filesystem'
    APP_SETTINGS_DATABASE_URL:        'mysql://symfonydev:!symfonydev@localhost:3306/symfonydev'
    APP_SETTINGS_MAILER_URL:          'smtp://127.0.0.1:1025?encryption=&auth_mode='
