parameters:
    APP_SETTINGS_APP_ENV:             'prod'
    APP_SETTINGS_APP_CODE:            'prod'
    APP_SETTINGS_APP_SECRET:          'TEMPORARY_SECRET'
    APP_SETTINGS_DATABASE_URL:        'sqlite:///%kernel.project_dir%/var-test/test.sqlite'
    APP_SETTINGS_MAILER_DSN:          'null://default'
    APP_SETTINGS_CACHE_APP:           'cache.adapter.filesystem'
    APP_SETTINGS_REDIS_CACHE_DB:      ''
    APP_SETTINGS_REDIS_CACHE_HOST:    ''
    APP_SETTINGS_REDIS_CACHE_PORT:    ''
    APP_SETTINGS_SESSION_HANDLER:     null
    APP_SETTINGS_REDIS_SESSION_DB:    ''
    APP_SETTINGS_REDIS_SESSION_HOST:  ''
    APP_SETTINGS_REDIS_SESSION_PORT:  ''
    # needed for functional tests
    APP_SETTINGS_APP_ENCRYPTOR_KEY_PAIR: '%env(APP_ENCRYPTOR_KEY_PAIR)%'
