controllers:
    resource: routing.controllers

spipu_user:
    resource: '@SpipuUserBundle/config/routes.yaml'

spipu_configuration:
    resource: '@SpipuConfigurationBundle/config/routes.yaml'

spipu_process:
    resource: '@SpipuProcessBundle/config/routes.yaml'