doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: 'mariadb-10.11.5'
        url: '%APP_SETTINGS_DATABASE_URL%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/App/Entity'
                prefix: 'App\Entity'
                alias: App
