imports:
- { resource: "@SpipuConfigurationBundle/Resources/config/spipu_configuration.yaml" }
- { resource: "@SpipuProcessBundle/Resources/config/spipu_configuration.yaml" }
- { resource: "@SpipuApiPartnerBundle/Resources/config/spipu_configuration.yaml" }

spipu_configuration:
    app.website.name:
        type:     string
        required: true
        default:  "Symfony Dev"

    api.partner.enabled:
        type:     "boolean"
        required: true
        default:  false

    api.partner.api_key:
        type:     "string"
        required: true
        default:  ""

    api.partner.api_secret:
        type:     "encrypted"
        required: true

    test.type.boolean:
        type:     boolean
        required: false

    test.type.color:
        type:     color
        required: false

    test.type.email:
        type:     email
        required: false

    test.type.encrypted:
        type:     encrypted
        required: true

    test.type.file:
        type: file
        required: false
        file_type: ['jpeg', 'jpg', 'png']
        help: "Only JPG and PNG files are allowed"

    test.type.float:
        type:     float
        required: false
        unit:     "Kg"

    test.type.integer:
        type:     integer
        required: false
        unit:     "cm"

    test.type.password:
        type:     password
        required: true

    test.type.select:
        type:     select
        options:  Spipu\UiBundle\Form\Options\YesNo
        required: true
        default:  "1"

    test.type.string:
      type: string
      required: false

    test.type.text:
        type: string
        required: true
        scoped: true
        default: "My text"

    test.type.url:
      type: url
      required: false