imports:
- { resource: "@SpipuConfigurationBundle/config/spipu_configuration.yaml" }
- { resource: "@SpipuProcessBundle/config/spipu_configuration.yaml" }

spipu_configuration:
    app.website.name:
        type:     string
        required: true
        default:  "Symfony Dev"

    test.type.encrypted:
        type:     encrypted
        required: true

    test.type.file:
        type: file
        required: false
        file_type: ['jpeg', 'jpg', 'png']
        help: "Only JPG and PNG files are allowed"

    test.type.password:
        type:     password
        required: true

    test.type.text:
        type:     string
        required: true
        scoped:   true
        default:  "My text"

    test.type.select:
        type:     select
        options:  Spipu\UiBundle\Form\Options\YesNo
        required: true
        default:  "1"

    test.type.boolean:
        type:     boolean
        required: true
        default:  "0"
