imports:
- { resource: "@SpipuConfigurationBundle/Resources/config/spipu_configuration.yaml" }
- { resource: "@SpipuProcessBundle/Resources/config/spipu_configuration.yaml" }

spipu_configuration:
    app.website.name:
        type:     string
        required: true
        default:  "Demo"

    app.website.logo:
        type: file
        required: false
        file_type: ['jpeg', 'png']