parameters:
  APP_SETTINGS_APP_ENV:                '{{ENV_MODE}}'
  APP_SETTINGS_APP_CODE:               '{{ENV_CODE}}'
  APP_SETTINGS_APP_SECRET:             '{{APP_SECRET}}'
  APP_SETTINGS_DATABASE_URL:           'mysql://{{DB_USER}}:{{DB_PASS}}@localhost:3306/{{DB_NAME}}'
  APP_SETTINGS_MAILER_DSN:             '{{APP_MAILER}}'
  APP_SETTINGS_CACHE_APP:              'cache.adapter.redis'
  APP_SETTINGS_REDIS_CACHE_DB:         '0'
  APP_SETTINGS_REDIS_CACHE_HOST:       'localhost'
  APP_SETTINGS_REDIS_CACHE_PORT:       '6379'
  APP_SETTINGS_SESSION_HANDLER:        '{{APP_SESSION_HANDLER}}'
  APP_SETTINGS_REDIS_SESSION_DB:       '0'
  APP_SETTINGS_REDIS_SESSION_HOST:     'localhost'
  APP_SETTINGS_REDIS_SESSION_PORT:     '6380'
  APP_SETTINGS_APP_ENCRYPTOR_KEY_PAIR: '{{APP_ENCRYPTOR_KEY_PAIR}}'
