parameters:
  paths:
      - ./src
  exclude_files:
    - '#.*/Spipu/CoreBundle/Tests/Kernel.php$#'
  layers:
    # APP Layer
    - name: App
      collectors:
        - type: className
          regex: App\\.*

    # Spipu Layer
    - name: Spipu
      collectors:
        - type: className
          regex: Spipu\\.*

  ruleset:
    # Global
    App:
      - Spipu
    Spipu: ~

