deptrac:
  paths:
      - ./src
  layers:
    # Bundle Layers
    - name: Spipu_ApiPartner
      collectors:
        - type: classLike
          value: Spipu\\ApiPartnerBundle\\.*
    - name: Spipu_Configuration
      collectors:
        - type: classLike
          value: Spipu\\ConfigurationBundle\\.*
    - name: Spipu_Core
      collectors:
        - type: classLike
          value: Spipu\\CoreBundle\\.*
    - name: Spipu_Dashboard
      collectors:
        - type: classLike
          value: Spipu\\DashboardBundle\\.*
    - name: Spipu_Process
      collectors:
        - type: classLike
          value: Spipu\\ProcessBundle\\.*
    - name: Spipu_Ui
      collectors:
        - type: classLike
          value: Spipu\\UiBundle\\.*
    - name: Spipu_User
      collectors:
        - type: classLike
          value: Spipu\\UserBundle\\.*

  ruleset:
    Spipu_Core: ~
    Spipu_Ui:
      - Spipu_Core
    Spipu_User:
      - Spipu_Core
      - Spipu_Ui
      - Spipu_Configuration
    Spipu_Configuration:
      - Spipu_Core
      - Spipu_Ui
    Spipu_Process:
      - Spipu_Core
      - Spipu_Ui
      - Spipu_Configuration
    Spipu_Dashboard:
      - Spipu_Core
      - Spipu_Ui
    Spipu_ApiPartner:
      - Spipu_Core
      - Spipu_Ui
      - Spipu_Configuration

  formatters:
    graphviz:
      point_to_groups: true
      groups: []
      hidden_layers: []
