phpqa:
    extensions:
        - php

phpcs:
    standard: .phpcs.xml
    allowedErrorsCount: 0
    ignoreWarnings: false
    reports:
        file:
            checkstyle: checkstyle.xml

phpmd:
    allowedErrorsCount: 0
    standard: .phpmd.xml

phpcpd:
    allowedErrorsCount: 0
    minLines: 5
    minTokens: 70

phpmetrics:
    config: null
    git: false

phpunit:
    allowedErrorsCount: 0
    binary: null
    config: .phpunit.xml
    reports:
        file: []
            # log: [junit, tap, json]
            # testdox: [html, text]
            # coverage: [html, clover, crap4j, php, text, xml] # requires XDebug extension

parallel-lint:
    allowedErrorsCount: 0


