spipu_process:
    this_is_a_process_with_a_very_long_name_for_tests:
        name: "This is a process with a very long name for tests"

        options:
            can_be_put_in_queue: true
            can_be_rerun_automatically: false
            process_lock:
                - "test_hello"
                - "test_sleep"
                - "this_is_a_process_with_a_very_long_name_for_tests"
            needed_role: "ROLE_ADMIN_PROCESS_BIG_NAME"

        steps:
            hello_world:
                class: Spipu\ProcessBundle\Step\Test\HelloWorld
                parameters:
                    name_from: "Foo"
                    name_to:   "Bar"
