spipu_process:
    test_input:
        name: "Test Input"

        options:
            can_be_put_in_queue: true
            can_be_rerun_automatically: true

        inputs:
            firstname:         "string"
            lastname:          "string"
            current_user_name: "string"
            test_int:          "int"
            test_float:        "float"
            test_bool:         "bool"
            test_array:        "array"
            test_optional_string:
                type:     "string"
                required: false
            test_option:
                type:     "string"
                options:  Spipu\ProcessBundle\Form\Options\Status
                required: true
            test_optional_option:
                type:     "string"
                options:  Spipu\ProcessBundle\Form\Options\Status
                required: false
            test_multi_option:
                type:     "array"
                options:  Spipu\ProcessBundle\Form\Options\Status
                required: true
            test_optional_multi_option:
                type:     "array"
                options:  Spipu\ProcessBundle\Form\Options\Status
                required: false
            test_file:
                type:    "file"
                allowed_mime_types: "application/pdf"

        parameters:
            my_firstname: "Foo"
            my_lastname:  "Bar"

        steps:
            name_from:
                class: Spipu\ProcessBundle\Step\String\MergeStrings
                parameters:
                    strings:
                      - "{{ my_firstname }}"
                      - "{{ my_lastname }}"
                    glue: " "

            name_to:
                class: Spipu\ProcessBundle\Step\String\MergeStrings
                parameters:
                    strings:
                      - "{{ input.firstname }}"
                      - "{{ input.lastname }}"
                    glue: " "

            sleep:
                class: Spipu\ProcessBundle\Step\Generic\Sleep
                parameters:
                    seconds: 2

            hello_world:
                class: Spipu\ProcessBundle\Step\Test\HelloWorld
                parameters:
                    name_from: "{{ result.name_from }}"
                    name_to:   "{{ result.name_to }}"
